routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    includeRouteFiles(__DIR__.'/Frontend/');
});


//$router->get( '/_debugbar/assets/stylesheets', '\Barryvdh\Debugbar\Controllers\AssetController@css' );
//$router->get( '/_debugbar/assets/javascript', '\Barryvdh\Debugbar\Controllers\AssetController@js' );

/* ----------------------------------------------------------------------- */

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    includeRouteFiles(__DIR__.'/Backend/');
});

app/Models/Access/Cars/Car.php
<?php

namespace App\Models\Access\Drivers;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{

    protected $table ="cars";

    protected $fillable = [
        'id', 'car_color', 'car_plaque', 'car_model', 'car_brand'
    ];
}

app/Models/Access/Clients/Client.php
<?php

namespace App\Models\Access\Clients;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Client
 * @package App\Models\Access\Clients
 */
class Client extends Model {

    protected $table ="clients";

    protected $fillable = ['id', 'user_id', 'mount_debt', 'trips_count'];


//    AuthApiController

    /**
     * An Client is owned by a user
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user() {
        return $this->belongsTo(User::class);
    }

}

app/Models/Access/Drivers/Driver.php
<?php

namespace App\Models\Access\Drivers;

use Illuminate\Database\Eloquent\Model;

class Driver extends Model
{

    protected $table ="drivers";

    protected $fillable = [
        'id', 'user_id', 'car_id', 'driver_past_location', 'driver_new_location', 'driver_state'
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function car() {
        return $this->belongsTo(Car::class);
    }
}

app/Models/Access/Payments/Payment.php
<?php

namespace App\Models\Access\PaymentsMethod;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $table ="payments";
    protected $fillable = [
        'id', 'user_id', 'trip_id', 'payment_method_id', 'amount', 'isApproved'
    ];

    public function user() {
        return $this->belongsTo('App\Models\Access\Users\User');
    }

    public function trip() {
        return $this->belongsTo('App\Models\Access\Trips\Trip');
    }

    public function payment_method() {
        return $this->belongsTo('App\Models\Access\PaymentsMethod\Payments_methods');
    }

}

app/Models/Access/PaymentsMethod/Payments_methods.php
<?php

namespace App\Models\Access\PaymentsMethod;

use Illuminate\Database\Eloquent\Model;

class Payments_methods extends Model
{
    protected $table ="payments_methods";

    protected $fillable = [
        'id', 'user_id', 'payment_type', 'isDefault', 'isActive'
    ];

    protected $hidden = ['card_type', 'card_number', 'card_security_number', 'card_holder_name', 'paypal_code'];

    public function user() {
        return $this->belongsTo('App\Models\Access\Users\User');
    }
}

app/Models/Access/Permission/Permission.php
<?php

namespace App\Models\Access\Permission;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Permission\Traits\Relationship\PermissionRelationship;

/**
 * Class Permission.
 */
class Permission extends Model
{
    use PermissionRelationship;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'display_name', 'sort'];

    /**
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = config('access.permissions_table');
    }
}

app/Models/Access/Permission/Traits/Relationship/PermissionRelationship.php
<?php

namespace App\Models\Access\Permission\Traits\Relationship;

/**
 * Class PermissionRelationship.
 */
trait PermissionRelationship
{
    /**
     * @return mixed
     */
    public function roles()
    {
        return $this->belongsToMany(config('access.role'), config('access.permission_role_table'), 'permission_id', 'role_id');
    }
}

app/Models/Access/Role/Role.php
<?php

namespace App\Models\Access\Role;

use App\Models\Access\Users\User;
use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Role\Traits\RoleAccess;
use App\Models\Access\Role\Traits\Scope\RoleScope;
use App\Models\Access\Role\Traits\Attribute\RoleAttribute;
use App\Models\Access\Role\Traits\Relationship\RoleRelationship;

/**
 * Class Role.
 */
class Role extends Model
{
    use RoleScope,
        RoleAccess,
        RoleAttribute,
        RoleRelationship;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'type', 'all', 'sort'];

    /**
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = config('access.roles_table');
    }

    // Role.php
//    public function foo() {
//        return $this->belongsToMany(Role::class, 'role_user', 'role_id', 'user_id');
//    }

}

app/Models/Access/Role/Traits/Attribute/RoleAttribute.php
<?php

namespace App\Models\Access\Role\Traits\Attribute;

/**
 * Class RoleAttribute.
 */
trait RoleAttribute
{
    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.access.role.edit', $this).'" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.edit').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        //Can't delete master admin role
        if ($this->id != 1) {
            return '<a href="'.route('admin.access.role.destroy', $this).'"
                data-method="delete"
                data-trans-button-cancel="'.trans('buttons.general.cancel').'"
                data-trans-button-confirm="'.trans('buttons.general.crud.delete').'"
                data-trans-title="'.trans('strings.backend.general.are_you_sure').'"
                class="btn btn-xs btn-danger"><i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="'.trans('buttons.general.crud.delete').'"></i></a>';
        }

        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return $this->edit_button.$this->delete_button;
    }
}

app/Models/Access/Role/Traits/Relationship/RoleRelationship.php
<?php

namespace App\Models\Access\Role\Traits\Relationship;

/**
 * Class RoleRelationship.
 */
trait RoleRelationship
{
    /**
     * @return mixed
     */
    public function users()
    {
        return $this->belongsToMany(config('auth.providers.users.model'), config('access.role_user_table'), 'role_id', 'user_id');
    }

    /**
     * @return mixed
     */
    public function permissions()
    {
        return $this->belongsToMany(config('access.permission'), config('access.permission_role_table'), 'role_id', 'permission_id')
            ->orderBy('display_name', 'asc');
    }
}

app/Models/Access/Role/Traits/RoleAccess.php
<?php

namespace App\Models\Access\Role\Traits;

/**
 * Class RoleAccess.
 */
trait RoleAccess
{
    /**
     * Save the inputted permissions.
     *
     * @param mixed $inputPermissions
     *
     * @return void
     */
    public function savePermissions($inputPermissions)
    {
        if (! empty($inputPermissions)) {
            $this->permissions()->sync($inputPermissions);
        } else {
            $this->permissions()->detach();
        }
    }

    /**
     * Attach permission to current role.
     *
     * @param object|array $permission
     *
     * @return void
     */
    public function attachPermission($permission)
    {
        if (is_object($permission)) {
            $permission = $permission->getKey();
        }

        if (is_array($permission)) {
            $permission = $permission['id'];
        }

        $this->permissions()->attach($permission);
    }

    /**
     * Detach permission form current role.
     *
     * @param object|array $permission
     *
     * @return void
     */
    public function detachPermission($permission)
    {
        if (is_object($permission)) {
            $permission = $permission->getKey();
        }

        if (is_array($permission)) {
            $permission = $permission['id'];
        }

        $this->permissions()->detach($permission);
    }

    /**
     * Attach multiple permissions to current role.
     *
     * @param mixed $permissions
     *
     * @return void
     */
    public function attachPermissions($permissions)
    {
        foreach ($permissions as $permission) {
            $this->attachPermission($permission);
        }
    }

    /**
     * Detach multiple permissions from current role.
     *
     * @param mixed $permissions
     *
     * @return void
     */
    public function detachPermissions($permissions)
    {
        foreach ($permissions as $permission) {
            $this->detachPermission($permission);
        }
    }
}

app/Models/Access/Role/Traits/Scope/RoleScope.php
<?php

namespace App\Models\Access\Role\Traits\Scope;

/**
 * Class RoleScope.
 */
trait RoleScope
{
    /**
     * @param $query
     * @param string $direction
     *
     * @return mixed
     */
    public function scopeSort($query, $direction = 'asc')
    {
        return $query->orderBy('sort', $direction);
    }
}

app/Models/Access/Settings/Setting.php
<?php

namespace App\Models\Access\Setting;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{

    protected $table ="settings";

    protected $fillable = [
        'distance_rate', 'minute_rate', 'minimun_rate', 'base_rate'
    ];

    protected $hidden = [
        'id', 'created_at', 'updated_at'
    ];
}

app/Models/Access/Trips/Trip.php
<?php

namespace App\Models\Access\Trips;

use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    protected $table ="trips";

    protected $fillable = [
        'id', 'user_client_id', 'user_drive_id', 'request_date', 'trip_date', 'origin_location', 'destiny_location', 'origin_name', 'destiny_name',
        'state', 'path_taked', 'trip_cost', 'trip_type', 'payment_id', 'isPaid', 'client_clasification', 'driver_clasification'
    ];

    protected $hidden = ['created_at', 'updated_at'];

    public function client() {
        return $this->belongsTo('App\Models\Access\Clients\Client');
    }

    public function driver() {
        return $this->belongsTo('App\Models\Access\Drivers\Driver');
    }
}

app/Models/Access/Users/SocialLogin.php
<?php

namespace App\Models\Access\Users;

use Illuminate\Database\Eloquent\Model;

/**
 * Class SocialLogin.
 */
class SocialLogin extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'social_logins';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id', 'provider', 'provider_id', 'token', 'avatar'];
}

app/Models/Access/Users/Traits/Relationship/UserRelationship.php
<?php

namespace App\Models\Access\Users\Traits\Relationship;

use App\Models\System\Session;
use App\Models\Access\Users\SocialLogin;

/**
 * Class UserRelationship.
 */
trait UserRelationship
{
    /**
     * Many-to-Many relations with Role.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany(config('access.role'), config('access.role_user_table'), 'user_id', 'role_id');
    }

    /**
     * @return mixed
     */
    public function providers()
    {
        return $this->hasMany(SocialLogin::class);
    }

    /**
     * @return mixed
     */
    public function sessions()
    {
        return $this->hasMany(Session::class);
    }
}

app/Models/Access/Users/Traits/Scope/UserScope.php
<?php

namespace App\Models\Access\Users\Traits\Scope;

/**
 * Class UserScope.
 */
trait UserScope
{
    /**
     * @param $query
     * @param bool $confirmed
     *
     * @return mixed
     */
    public function scopeConfirmed($query, $confirmed = true)
    {
        return $query->where('confirmed', $confirmed);
    }

    /**
     * @param $query
     * @param bool $status
     *
     * @return mixed
     */
    public function scopeActive($query, $status = true)
    {
        return $query->where('status', $status);
    }
}

app/Models/Access/Users/Traits/UserSendPasswordReset.php
<?php

namespace App\Models\Access\Users\Traits;

use App\Notifications\Frontend\Auth\UserNeedsPasswordReset;

/**
 * Class UserSendPasswordReset.
 */
trait UserSendPasswordReset
{
    /**
     * Send the password reset notification.
     *
     * @param string $token
     *
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new UserNeedsPasswordReset($token));
    }
}

resources/views/backend/access/chofer/change-password.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.access.users.management-clients') . ' | ' . trans('labels.backend.access.users.change_password'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.access.users.management-clients') }}
        <small>{{ trans('labels.backend.access.users.change_password') }}</small>
    </h1>
@endsection

@section('content')
    {{ Form::open(['route' => ['admin.access.user.change-password.post', $user], 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'patch']) }}

        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">{{ trans('labels.backend.access.users.change_password_for', ['user' => $user->name]) }}</h3>

                <div class="box-tools pull-right">
                    @include('backend.access.includes.partials.user-header-buttons')
                </div><!--box-tools pull-right-->
            </div><!-- /.box-header -->

            <div class="box-body">
                <div class="form-group">
                    {{ Form::label('password', trans('validation.attributes.backend.access.users.password'), ['class' => 'col-lg-2 control-label', 'placeholder' => trans('validation.attributes.backend.access.users.password')]) }}

                    <div class="col-lg-10">
                        {{ Form::password('password', ['class' => 'form-control', 'required' => 'required', 'autofocus' => 'autofocus']) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('password_confirmation', trans('validation.attributes.backend.access.users.password_confirmation'), ['class' => 'col-lg-2 control-label', 'placeholder' => trans('validation.attributes.backend.access.users.password_confirmation')]) }}

                    <div class="col-lg-10">
                        {{ Form::password('password_confirmation', ['class' => 'form-control', 'required' => 'required']) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->
            </div><!-- /.box-body -->
        </div><!--box-->

        <div class="box box-info">
            <div class="box-body">
                <div class="pull-left">
                    {{ link_to_route('admin.access.user.index', trans('buttons.general.cancel'), [], ['class' => 'btn btn-danger btn-xs']) }}
                </div><!--pull-left-->

                <div class="pull-right">
                    {{ Form::submit(trans('buttons.general.crud.update'), ['class' => 'btn btn-success btn-xs']) }}
                </div><!--pull-right-->

                <div class="clearfix"></div>
            </div><!-- /.box-body -->
        </div><!--box-->

    {{ Form::close() }}
@endsection

resources/views/backend/access/chofer/deactivated.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.access.users.management-clients') . ' | ' . trans('labels.backend.access.users.deactivated'))

@section('after-styles')
    {{ Html::style("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css") }}
@endsection

@section('page-header')
    <h1>
        {{ trans('labels.backend.access.users.management-clients') }}
        <small>{{ trans('labels.backend.access.users.deactivated') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.access.users.deactivated') }}</h3>

            <div class="box-tools pull-right">
                @include('backend.access.includes.partials.user-header-buttons')
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">
            <div class="table-responsive">
                <table id="users-table" class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>{{ trans('labels.backend.access.users.table.last_name') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.first_name') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.email') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.confirmed') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.roles') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.created') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.last_updated') }}</th>
                            <th>{{ trans('labels.general.actions') }}</th>
                        </tr>
                    </thead>
                </table>
            </div><!--table-responsive-->
        </div><!-- /.box-body -->
    </div><!--box-->
@endsection

@section('after-scripts')
    {{ Html::script("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js") }}
    {{ Html::script("js/backend/plugin/datatables/dataTables-extend.js") }}

    <script>
        $(function() {
            $('#users-table').DataTable({
                dom: 'lfrtip',
                processing: false,
                serverSide: true,
                autoWidth: false,
                ajax: {
                    url: '{{ route("admin.access.user.get") }}',
                    type: 'post',
                    data: {status: 0, trashed: false},
                    error: function (xhr, err) {
                        if (err === 'parsererror')
                            location.reload();
                    }
                },
                columns: [
                    {data: 'last_name', name: '{{config('access.users_table')}}.last_name'},
                    {data: 'first_name', name: '{{config('access.users_table')}}.first_name'},
                    {data: 'email', name: '{{config('access.users_table')}}.email'},
                    {data: 'confirmed', name: '{{config('access.users_table')}}.confirmed'},
                    {data: 'roles', name: '{{config('access.roles_table')}}.name', sortable: false},
                    {data: 'created_at', name: '{{config('access.users_table')}}.created_at'},
                    {data: 'updated_at', name: '{{config('access.users_table')}}.updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>
@endsection

resources/views/backend/access/chofer/index.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.access.users.management-choferes'))

@section('after-styles')
    {{ Html::style("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css") }}
@endsection

@section('page-header')
    <h1>
        {{ trans('labels.backend.access.users.management-choferes') }}
        <small>{{ trans('labels.backend.access.cliente.active') }}</small>
    </h1>
@endsection

@section('content')
    {{--@include('backend.access.includes.partials.user-header-buttons')--}}
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.access.choferes.active') }}</h3>

            {{--<div class="box-tools pull-right">--}}
                {{--@include('backend.access.includes.partials.user-header-buttons')--}}
            {{--</div><!--box-tools pull-right-->--}}
        </div><!-- /.box-header -->

        <div class="box-body">


            <table style="text-align: center;" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th style="text-align: center;">Nombre</th>
                    <th style="text-align: center;">Apellido</th>
                    <th style="text-align: center;">Correo</th>
                    <th style="text-align: center;">Rol</th>
                    <th style="text-align: center;">Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($usuarios as $user)
                    <tr>

                        <td>{!! $user->first_name !!}</td>
                        <td>{!! $user->last_name !!}</td>
                        <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                        <td>
                            @if ($user->roles()->count() > 0)
                                @foreach ($user->roles as $role)
                                    {!! $role->name !!}<br/>
                                @endforeach
                            @else
                                Ninguno
                            @endif
                        </td>
                        <td>{!! $user->action_buttons !!}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            {{--<div class="table-responsive">--}}
                {{--<table id="users-table" class="table table-condensed table-hover">--}}
                    {{--<thead>--}}
                    {{--<tr>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.first_name') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.last_name') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.email') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.confirmed') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.roles') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.social') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.created') }}</th>--}}
                        {{--<th>{{ trans('labels.backend.access.users.table.last_updated') }}</th>--}}
                        {{--<th>{{ trans('labels.general.actions') }}</th>--}}
                    {{--</tr>--}}
                    {{--</thead>--}}
                {{--</table>--}}
            {{--</div><!--table-responsive-->--}}
        </div><!-- /.box-body -->
    </div><!--box-->

    {{--<div class="box box-info">--}}
        {{--<div class="box-header with-border">--}}
            {{--<h3 class="box-title">{{ trans('history.backend.recent_history') }}</h3>--}}
            {{--<div class="box-tools pull-right">--}}
                {{--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>--}}
            {{--</div><!-- /.box tools -->--}}
        {{--</div><!-- /.box-header -->--}}
        {{--<div class="box-body">--}}
            {{--{!! history()->renderType('User') !!}--}}
        {{--</div><!-- /.box-body -->--}}
    {{--</div><!--box box-success-->--}}
@endsection

@section('after-scripts')
    {{--{{ Html::script("https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js") }}--}}
    {{--<script src="https://datatables.yajrabox.com/js/jquery.min.js"></script>--}}
    <script src="https://datatables.yajrabox.com/js/bootstrap.min.js"></script>
    <script src="https://datatables.yajrabox.com/js/jquery.dataTables.min.js"></script>
    <script src="https://datatables.yajrabox.com/js/datatables.bootstrap.js"></script>
    <script type="text/javascript">

            {{--$("#cliente").DataTable({--}}
                {{--"processing": true,--}}
                {{--"serverSide": true,--}}
                {{--"ajax": "{{ route('admin.access.cliente.gets') }}",--}}
                {{--"columns": [--}}
                    {{--{data: 'last_name', name: 'last_name'},--}}
{{--//--}}
                {{--]--}}
            {{--});--}}

    </script>
    {{--{{ Html::script("js/backend/plugin/datatables/dataTables-extend.js") }}--}}

    <script>
        $('#cliente').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{route("admin.access.cliente.gets")}}',

            columns: [
//                {data: 'id', name: 'id'},
//                {data: 'name', name: 'name'},
                {data: 'email'},
//                {data: 'created_at', name: 'created_at'},
//                {data: 'updated_at', name: 'updated_at'},
//                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

        {{--$(function () {--}}
            {{--$('#cliente').DataTable({--}}
                {{--"language": {--}}
                    {{--"sProcessing":     "Procesando...",--}}
                    {{--"sLengthMenu":     "Mostrar _MENU_ registros",--}}
                    {{--"sZeroRecords":    "No se encontraron resultados",--}}
                    {{--"sEmptyTable":     "Ningún dato disponible en esta tabla",--}}
                    {{--"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",--}}
                    {{--"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",--}}
                    {{--"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",--}}
                    {{--"sInfoPostFix":    "",--}}
                    {{--"sSearch":         "Buscar:",--}}
                    {{--"searchPlaceholder": "Clientes",--}}
                    {{--"sUrl":            "",--}}
                    {{--"sInfoThousands":  ",",--}}
                    {{--"sLoadingRecords": "Cargando...",--}}
                    {{--"oPaginate": {--}}
                        {{--"sFirst":    "Primero",--}}
                        {{--"sLast":     "Último",--}}
                        {{--"sNext":     "Siguiente",--}}
                        {{--"sPrevious": "Anterior"--}}
                    {{--},--}}
                    {{--"oAria": {--}}
                        {{--"sSortAscending":  ": Activar para ordenar la columna de manera ascendente",--}}
                        {{--"sSortDescending": ": Activar para ordenar la columna de manera descendente"--}}
                    {{--}--}}
                {{--},--}}
{{--//                dom: 'lfrtip',--}}
                {{--processing: true,--}}
                {{--serverSide: true,--}}
                {{--autoWidth: false,--}}
                {{--ajax: {--}}
                    {{--url: '{{ route("admin.access.cliente.gets") }}',--}}
                    {{--type: 'post',--}}
                    {{--data: {status: 1, trashed: false},--}}
                    {{--error: function (xhr, err) {--}}
                        {{--if (err === 'parsererror')--}}
                            {{--location.reload();--}}
                    {{--}--}}
                {{--},--}}
                {{--columns: [--}}
                    {{--{data: 'first_name', name: 'first_name'},--}}
{{--//                    {data: 'last_name', name: 'last_name'},--}}
{{--//                    {data: 'email', name: 'email'},--}}
{{--//                    {data: 'confirmed', name: 'confirmed'},--}}
{{--//                    {data: 'roles', name: 'name', sortable: false},--}}
{{--////                    {data: 'social', name: 'social', sortable: false},--}}
{{--//                    {data: 'created_at', name: 'created_at'},--}}
{{--//                    {data: 'updated_at', name: 'updated_at'},--}}
{{--//                    {data: 'actions', name: 'actions', searchable: false, sortable: false}--}}
                {{--],--}}
                {{--order: [[0, "asc"]],--}}
                {{--searchDelay: 500--}}
            {{--});--}}
        {{--});--}}
    {{--</script>--}}
@endsection